title: Rules Engine
description: Taking action one criterion at a time
show_downloads: false
google_analytics:
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
github:
  repository_url: https://github.com/robert-f-ruff/rules_engine
  owner_name: Robert F. Ruff
  zip_url:
  tar_url:
